NETWORK_FILE = 'data/network.json'
SPHERES_SIZE = 0.003
SPHERES_NUM_SEGMENTS = 8
SPHERES_NUM_RINGS = 4
CHANNELS_RADIUS = 0.002
CHANNELS_RESOLUTION = 2

ANIMATION_FILE = 'data/animation.json'
# Values in seconds.
ANIMATION_LENGTH_SHOW = 0.1
ANIMATION_LENGTH_FLASH = 5.0
ANIMATION_LENGTH_HIDE = 0.1

ANIMATION_DEPTH = 50

TRANSFER_COLOR = (0.0, 0.5, 1.0, 1.0)
